// ********RoostGPT********
/*
Test generated by RoostGPT for test rest-assured-loader-testing using AI Type Open AI and AI Model gpt-4

Test generated for /employees_post for http method type POST in rest-assured framework

RoostTestHash=b517afeac4


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class employeesPostTest {

    List<Map<String, String>> envList = new ArrayList<>();


    @Before
    public void setUp() {
      TestdataLoader dataloader = new TestdataLoader();
      envList = dataloader.loadData("src/test/java/com/bootexample4/RoostTest/employeesPostTest.csv");
    }

  
    @Test  
    public void employeesPost_Test() {
        this.setUp();
        for (Map<String, String> map : envList) {
          RestAssured.baseURI = map.get("BASE_URL");  
  
                Response response = given()
				.contentType(ContentType.JSON)
				.body("{\n"+
					"  \"id\": \"" + (map.get("id") != null ? map.get("id") : "") + "\",\n" +
					"  \"jobTitle\": \"" + (map.get("jobTitle") != null ? map.get("jobTitle") : "") + "\",\n" +
					"  \"name\": \"" + (map.get("name") != null ? map.get("name") : "") + "\",\n" +
					"  \"email\": \"" + (map.get("email") != null ? map.get("email") : "") + "\n" +
 				"}")
                .when()
                .post("/employees")  
                .then() 
                .extract().response();    
         
                if (response.statusCode() == 201) {
					System.out.println("Description: employee created");
				}
if (response.statusCode() == 400) {
					System.out.println("Description: invalid input, object invalid");
				}
if (response.statusCode() == 409) {
					System.out.println("Description: an existing employee already exists");
				}
  
            }  
    }
}
