// ********RoostGPT********
/*
Test generated by RoostGPT for test productOrder-restassured using AI Type Open AI and AI Model gpt-4

Test generated for /listener/productOrderInformationRequiredEvent_post for http method type POST in rest-assured framework

RoostTestHash=e74b642c2e


*/

// ********RoostGPT********

@BeforeEach
public void setUp() {
    try {
        TestdataLoader dataloader = new TestdataLoader();
        String[] envVarsList = { "BASE_URL" };
        envList = dataloader.load(
            "src/test/java/com/bootexample4/RoostTest/listener_productOrderInformationRequiredEventPostTest.csv",
            envVarsList);
    } catch (IOException e) {
        System.out.println("Error reading test data file");
        e.printStackTrace();
    }
}
