// ********RoostGPT********
/*
Test generated by RoostGPT for test productOrder-restassured using AI Type Open AI and AI Model gpt-4

Test generated for /productOrder/{order.Id}_patch for http method type PATCH in rest-assured framework

RoostTestHash=baabcd7d73


*/

// ********RoostGPT********

switch (Integer.toString(responseObj.statusCode()).charAt(0)) {

}
