// ********RoostGPT********
/*
Test generated by RoostGPT for test productOrder-restassured using AI Type Open AI and AI Model gpt-4

Test generated for /productOrder_post for http method type POST in rest-assured framework

RoostTestHash=13e6a9adf7


*/

// ********RoostGPT********

package com.bootexample4.RoostTest;

// imports...

public class ProductOrderPostTest {

    // all your code remains the same...

}
